### ISSUE TITLE
Error in appdeamon ligs

### ISSUE THREAD

**Issue by w1tw0lf** [Mohlsson/ReplayLightsHistory#2]
Getting the following errors
`2020-02-02 08:40:35.285584 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/replay_lights.py
2020-02-02 08:40:35.289347 WARNING Error: ------------------------------------------------------------
2020-02-02 08:40:35.290279 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/replay_lights.py:
2020-02-02 08:40:35.291258 WARNING Error: ------------------------------------------------------------
2020-02-02 08:40:35.295300 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 788, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 580, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/replay_lights.py", line 26
    for row in c.execute(f'SELECT event_data FROM events WHERE time_fired > datetime("now","localtime","-{self.numberOfDaysBack} days","+1 minutes") AND time_fired < datetime("now","localtime","-{self.numberOfDaysBack} days","+61 minut$        try:`

in appdeamon it shows the app has terminated.

**Comment by Mohlsson** [comment]
Are you using the default SQLite database for Home Assistant?

**Comment by w1tw0lf** [comment]
Yip, default SQLite

**Comment by w1tw0lf** [comment]
Just had a look at replay_lights.py and seems for me that lin 26 is missing things at the end of the line.

`for row in c.execute(f'SELECT event_data FROM events WHERE time_fired > datetime("now","localtime","-{self.numberOfDaysBack} days","+1 minutes") AND time_fired < datetime("now","localtime","-{self.numberOfDaysBack} days","+61 minut$        try:`

**Comment by Mohlsson** [comment]
Oups, I did commit with a truncated line. Fixed now, please try again.

**Comment by w1tw0lf** [comment]
Thanks that solved that part.
